name: "weather_gencast_demo_model"
backend: "python"

input [
  {
    name: "input_nc"
    data_type: TYPE_BYTES
    dims: [1]
  }
]

output [
  {
    name: "output_array"
    data_type: TYPE_FP32
    dims: [ 1 , 2, 3, 4 ]  # Shape of output
  }
]

instance_group [
  {
    kind: KIND_GPU
  }
]
