name: "satvision_toa_model"
backend: "pytorch"
max_batch_size: 8

input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [14, 128, 128]
  }
]

output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [1, 128, 128]
  }
]
