name: "satvision_toa_model"
platform: "pytorch_libtorch"
max_batch_size: 0
input [
  {
    name: "image"
    data_type: TYPE_FP32
    dims: [1, 14, 128, 128]
  },
  {
    name: "mask"
    data_type: TYPE_BOOL
    dims: [1, 32, 32]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [1]
  }
]
