name: "weather_aurora_demo_model"
backend: "python"
max_batch_size: 0

input [
  { name: "surf_vars_2t" data_type: TYPE_FP32 dims: [1, 2, 17, 32] },
  { name: "surf_vars_10u" data_type: TYPE_FP32 dims: [1, 2, 17, 32] },
  { name: "surf_vars_10v" data_type: TYPE_FP32 dims: [1, 2, 17, 32] },
  { name: "surf_vars_msl" data_type: TYPE_FP32 dims: [1, 2, 17, 32] },

  { name: "static_vars_lsm" data_type: TYPE_FP32 dims: [17, 32] },
  { name: "static_vars_z" data_type: TYPE_FP32 dims: [17, 32] },
  { name: "static_vars_slt" data_type: TYPE_FP32 dims: [17, 32] },

  { name: "atmos_vars_z" data_type: TYPE_FP32 dims: [1, 2, 4, 17, 32] },
  { name: "atmos_vars_u" data_type: TYPE_FP32 dims: [1, 2, 4, 17, 32] },
  { name: "atmos_vars_v" data_type: TYPE_FP32 dims: [1, 2, 4, 17, 32] },
  { name: "atmos_vars_t" data_type: TYPE_FP32 dims: [1, 2, 4, 17, 32] },
  { name: "atmos_vars_q" data_type: TYPE_FP32 dims: [1, 2, 4, 17, 32] },

  { name: "metadata_lat" data_type: TYPE_FP32 dims: [17] },
  { name: "metadata_lon" data_type: TYPE_FP32 dims: [32] },
  { name: "metadata_time" data_type: TYPE_FP32 dims: [1] },
  { name: "metadata_atmos_levels" data_type: TYPE_FP32 dims: [4] }
]
output [
  # surf_vars
  { name: "surf_vars_2t" data_type: TYPE_FP32 dims: [17, 32] },
  { name: "surf_vars_10u" data_type: TYPE_FP32 dims: [17, 32] },
  { name: "surf_vars_10v" data_type: TYPE_FP32 dims: [17, 32] },
  { name: "surf_vars_msl" data_type: TYPE_FP32 dims: [17, 32] },

  # static_vars
  { name: "static_vars_lsm" data_type: TYPE_FP32 dims: [17, 32] },
  { name: "static_vars_z" data_type: TYPE_FP32 dims: [17, 32] },
  { name: "static_vars_slt" data_type: TYPE_FP32 dims: [17, 32] },

  # atmos_vars
  { name: "atmos_vars_z" data_type: TYPE_FP32 dims: [17, 32] },
  { name: "atmos_vars_u" data_type: TYPE_FP32 dims: [17, 32] },
  { name: "atmos_vars_v" data_type: TYPE_FP32 dims: [17, 32] },
  { name: "atmos_vars_t" data_type: TYPE_FP32 dims: [17, 32] },
  { name: "atmos_vars_q" data_type: TYPE_FP32 dims: [17, 32] }

]
instance_group [
  { kind: KIND_GPU }
]
